# Generated by Django 5.2 on 2025-05-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', verbose_name='Основное изображение'),
        ),
    ]
