# Generated by Django 5.2 on 2025-05-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_project_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Срок выполнения (семестры)'),
        ),
    ]
